tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
  - name: postgres
    init: |
      curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
      echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
      sudo apt update
      sudo apt install -y postgresql-client-13 libpq-dev
    command: |
      export GITPOD_IP=$(curl ifconfig.me)
      source  "$THEIA_WORKSPACE_ROOT/backend_flask/bin/rds-update-sg-rule"
  - name: npm install
    init: |
      cd /workspace/aws-bootcamp-cruddur-2023/frontend-react-js
      npm install && npm install -g eslint
      cd $THEIA_WORKSPACE_ROOT
  - name: snyk
    init: |
      cd /workspace
      npm install snyk -g
      cd $THEIA_WORKSPACE_ROOT
  - name: backend-flask
    init: |
      cd /workspace
      pip install -r aws-bootcamp-cruddur-2023/backend_flask/requirements.txt
      cd $THEIA_WORKSPACE_ROOT
      export FLASK_ADDRESS="https://4567-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      export ENABLE_XRAY_LOG=""
      export ENABLE_CLOUDWATCH_LOG=""
      export ENABLE_ROLLBAR_LOG=""
      export ENABLE_HONEYCOMB_LOG=""
vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - ms-azuretools.vscode-docker
    - cweijan.vscode-postgresql-client2
    - dbaeumer.vscode-eslint
    - xabikos.JavaScriptSnippets
    - ckolkman.vscode-postgres
ports:
  - name: frontend
    port: 3000
    onOpen: open-browser
    visibility: public
  - name: backend
    port: 4567
    onOpen: open-browser
    visibility: public
  - name: xray-daemon
    port: 2000
    visibility: public
